### ISSUE TITLE
bold.dk

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#1632]
### Basic Information

**Test link:** `https://www.bold.dk/video/?id=590695`
**Category:** anti-adblock
**Reported from:** Denmark
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
**Extension:** Nano Defender 15.0.0.158

### Additional Message

Original URL: `https://jspenguin2017.github.io/uBlockProtector/#reporting-an-issue`

It happens on every single video being hosted on this site. 

In english:

"The program cannot be played.

The program cannot be played. Check your connection or disable your adblocker, if you have one installed. Refresh the page once your adblocker is disabled."

**Comment by llacb47** [comment]
Fixed in regional lists, but...

```
@@||fwmrm.net/crossdomain.xml$xhr,domain=viafree.no|viafree.dk
@@||fwmrm.net/libs/adm/*/AdManager.js$script,domain=viafree.dk|viafree.no
```

Entries from `https://github.com/DandelionSprout/adfilt/blob/master/NorwegianExperimentalList%20alternate%20versions/NordicFiltersABP.txt`

**Comment by jspenguin2017** [comment]
Fixed by Norwegian regional filters.

**Comment by NanoMeow** [comment]
### Basic Information

**Test link:** `https://www.bold.dk/video/?id=596675`
**Category:** anti-adblock
**Reported from:** Denmark
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
**Extension:** Nano Defender 15.0.0.170

### Additional Message

**Comment by mapx-** [comment]
`@@||5d402.v.fwmrm.net/ad/$script,domain=viafree.dk`

@DandelionSprout

**Comment by DandelionSprout** [comment]
I am by no means an expert on `fwmrm`'s prefix domains, but I presumed that it'd likely be a more safe bet to make the entry non-prefix-depending. I am however unable to test it myself due to every single non-YouTube video on that site being region-locked.

@lassekongo83 Since we're mostly synchronising our `Viafree` entries by now: Do you think that 3rd-party sites using `Viafree` would be enough of a problem in Sweden as well that you'd want to change `@@||fwmrm.net/ad/$image,xhr,domain=viafree.se` to `@@||fwmrm.net/ad/$image,xhr,script,domain=viafree.se` in your Swedish list?

**Comment by lassekongo83** [comment]
`fwmrm.net/ad/g/` script for the Swedish version of the site is already whitelisted in easylist.
