### ISSUE TITLE
soccer-live.stream

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#168]
### Basic Information

**Test link:** `https://soccer-live.stream/antalyaspor-vs-galatasaray-live/stream-1`
**Category:** anti-adblock
**Reported from:** Turkey
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
**Extension:** Nano Defender 15.0.0.51

### Additional Message

said "disable adblock and refresh". I guess it countered the defender

**Comment by jspenguin2017** [comment]
@okiehsch Popup ads. Too hard to test anything else with all these popups.

**Comment by okiehsch** [comment]
````
||easylist.pw/js/*$xmlhttprequest,domain=soccer-live.stream`
||oagwl3372h.com^$third-party
````
I do not see any anti-adblock message.

**Comment by mapx-** [comment]
I get no video running, is it normal ? (even disabling uBo)

**Comment by jspenguin2017** [comment]
Yea, stream haven't started yet.

**Comment by okiehsch** [comment]
The whole website is a mess your csp will break video playback on some stream, because they use different iframes to embed streams and they also change them all the time.
They also use domains like `ublock.pw` and `easlist.pw` 😆 
`https://soccer-live.stream/montreal-impact-vs-columbus-crew-live/stream-1`
is a working stream on my end, but you have to disable the csp.

**Comment by mapx-** [comment]
yes, enough using these ones
```
soccer-live.stream##+js(window.open-defuser.js)
soccer-live.stream##.btn-danger
soccer-live.stream##.btn-info
soccer-live.stream##.btn-primary.btn
```

**Comment by okiehsch** [comment]
I would say 
````
soccer-live.stream##+js(window.open-defuser.js)
camlive.pw##+js(nowebrtc.js)
||easylist.pw/js/*$xmlhttprequest,domain=soccer-live.stream
||oagwl3372h.com^$third-party
soccer-live.stream##.btn-danger
soccer-live.stream##.btn-info
````

**Comment by mapx-** [comment]
yep, @okiehsch  it looks well with yours (ads on the right side blocked as well)

**Comment by okiehsch** [comment]
Fixed.

**Comment by ArabCoders** [comment]
dunno if this is intended, this new filter specially this part
```
##.btn-info
##.btn-danger
##.btn-primary.btn
```

is breaking alot of bootstrap 4 websites that uses those buttons such as

```
<button type="submit" class="btn btn-primary">
Submit
</button>
````

all those buttons are hidden not sure exactly why this filter is being applied to different websites instead of this specific one.

hell, even github submit button is gone!

![github image](https://user-images.githubusercontent.com/1621552/46580412-24878380-ca2d-11e8-92ad-c27e31538082.png)

@jspenguin2017

**Comment by mapx-** [comment]
fixed
https://github.com/uBlockOrigin/uAssets/commit/efb98870510f5731b53f45f2bb76723eb3b31188

**Comment by ArabCoders** [comment]
@mapx- thanks for the quick response.
