### ISSUE TITLE
corneey.com

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#333]
### Basic Information

**Test link:** `http://corneey.com/wLknXW`
**Category:** breakage
**Reported from:** Mexico
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:63.0) Gecko/20100101 Firefox/63.0
**Extension:** Nano Defender 15.0.0.72

### Additional Message

Nano defender doesnt allow the captcha loading in firefox

**Comment by jspenguin2017** [comment]
Works fine for me. @LiCybora 
![image](https://user-images.githubusercontent.com/7283682/48663430-4113d400-ea4d-11e8-8135-19f5e07a1320.png)

**Comment by LiCybora** [comment]
I guess I have quick fix for it, but the fix may affect Chromium and Edge. The problem is Firefox treated `webRequest.onBeforeSendHeaders` as  asynchronous event listeners, while both Chromium and Edge does not support asynchronous event listener (just from MDN notes, I don't have them to test with). I will include the fix in v15.0.0.74 first anyway.

Reference:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders

**Comment by jspenguin2017** [comment]
I thought `chrome` namespace only accept synchronous handlers or asynchronous handlers with callbacks, and `browser` namespace are for asynchronous handlers with promise. 

Are you sure the timer bypassing is still working after the change? Maybe edit the user agent to Google Bot or something?

**Comment by jspenguin2017** [comment]
Hum, I might want to try a bot user agent, maybe it goes through the timer and verification altogether.

**Comment by LiCybora** [comment]
Yes I tried Google bot and curl UA, both bypass timer and verification, directly forward to target link.
I am not sure whether all sites in the rule will work in the same way

**Comment by jspenguin2017** [comment]
Fixed.
