### ISSUE TITLE
rtl.hr

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#4559]
### Basic Information

**Test link:** `https://www.rtl.hr/`
**Category:** anti-adblock
**Reported from:** Croatia
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.206
**Extension:** Nano Defender 15.0.0.205

### Additional Message

You are seeing this message because ad or script blocking software is interfering with this page.

**Comment by DandelionSprout** [comment]
This seems to be yet another one of those weird cases where the AAB only shows up if EasyPrivacy is turned *off*... except now I can also reproduce it with a stock list setup. And to my surprise, it appears that merely adding `||googletagmanager.com/gtm.js$script` doesn't remove it either, despite this being the de facto fix that the uAssets team came up with when I discussed this with them.

I see only 2 possible solutions to this report:
* Convince uAssets that `||fundingchoicesmessages.google.com^$3p` should be removed from uAssets Main.
* Have uAssets or Nano Filters add `##div[style^="bottom: 0px;"][style*="width: 10"][style*="z-index: 2147"]` as a *generic* entry, because this exact AAB message and situation has also occured to me on `recordere.dk`, `abcnyheter.no` and `aftenposten.no` within the past week.

**Comment by DandelionSprout** [comment]
![image](https://user-images.githubusercontent.com/22780683/91642749-26e29480-ea2e-11ea-9345-84e4da9c36b3.png)

**Comment by llacb47** [comment]
https://github.com/uBlockOrigin/uAssets/commit/22b929fbf29eda9c4cbb4ca35becd99325682fb4
