### ISSUE TITLE
urlgalleries.net

### ISSUE THREAD

**Issue by NanoMeow** [NanoMeow/QuickReports#733]
### Basic Information

**Test link:** `https://urlgalleries.net`
**Category:** anti-adblock
**Reported from:** United States
**Template version:** 2

### User Environment

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.56 Safari/537.36
**Extension:** Nano Defender 15.0.0.102

### Additional Message

[NSFW]

Click around on the site a bit with ublock origin and then you're greeted with this: `https://i.imgur.com/hAhudGi.png`

Example link: `https://unlimitedgalleries.urlgalleries.net/porn-gallery-7482451/Jillian-McCarty-Set-02-FF-`

Would appreciate a fix if possible

**Comment by okiehsch** [comment]
Fixed.

**Comment by bobsage123** [comment]
Hi, I think this fix might need to be applied to *.urlgalleries.net and not just `unlimitedgalleries.urlgalleries.net` since the site uses a bunch of prefixes. See below for an example of another.

I updated my filters and noticed the fix applied then went to this page and clicked an image and got the warning again - `https://xxnx.urlgalleries.net/porn-gallery-7482457/Mirren-%5Bx83%5D`

https://i.imgur.com/G2UP1hG.png

**Comment by okiehsch** [comment]
Thanks, updated.
